# Generated by Django 4.1.5 on 2023-01-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
