# Generated by Django 4.1.5 on 2023-01-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_manager', '0002_task_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Project',
            new_name='project',
        ),
    ]
